/* ============================================================
   FILE:      sql/07_agentic/02_agent_service_user.sql
   PURPOSE:   Least-privilege role and service user for the agent backend
   RUN AFTER: sql/07_agentic/01_order_risk_view.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS AGENT_ROLE;

GRANT USAGE ON WAREHOUSE SUPPLY_TRUST_WH TO ROLE AGENT_ROLE;
GRANT USAGE ON DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;

-- Read-only for now; write access is added per procedure in Step 4
GRANT SELECT ON ALL TABLES IN DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;
GRANT SELECT ON ALL VIEWS  IN DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE SUPPLY_TRUST_DB TO ROLE AGENT_ROLE;

-- Allows AI_COMPLETE
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AGENT_ROLE;

CREATE USER IF NOT EXISTS AGENT_SERVICE_USER
    TYPE = SERVICE
    DEFAULT_ROLE = AGENT_ROLE
    DEFAULT_WAREHOUSE = SUPPLY_TRUST_WH
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArMLsrXFrUMfuxL2v9BUvQj+d1yeiS+MKAQkE3YWb2Lz5m0BE2npp0aqdBnoFEFPe7FVHW+i8rbmob50PIWm0GTFtHWVk/i1mUQDbH8stm8p9Cgul4BORdkLLa0kqOJc3GSEO76KrK8cp8IP/vmbo9JHiB5QmBQYl+amK7Gv6/XE8I9ZgOswBTFi5M7Kc21Oe2eAN4FXltFTlgaNHaKYFL960K9qeLb4hytxkQ42ccsTVkWgmzlER3NHwgeVh+6+VXdvADwHe0mGlJ8pfoQ2aC6AMJC1QEKUgw10Qqqd8I2ctezCqM3mQFdEGX+p0T5bwIEhYfcK7wRYtu9YmRBAxLQIDAQAB';

ALTER USER AGENT_SERVICE_USER
    SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArMLsrXFrUMfuxL2v9BUvQj+d1yeiS+MKAQkE3YWb2Lz5m0BE2npp0aqdBnoFEFPe7FVHW+i8rbmob50PIWm0GTFtHWVk/i1mUQDbH8stm8p9Cgul4BORdkLLa0kqOJc3GSEO76KrK8cp8IP/vmbo9JHiB5QmBQYl+amK7Gv6/XE8I9ZgOswBTFi5M7Kc21Oe2eAN4FXltFTlgaNHaKYFL960K9qeLb4hytxkQ42ccsTVkWgmzlER3NHwgeVh+6+VXdvADwHe0mGlJ8pfoQ2aC6AMJC1QEKUgw10Qqqd8I2ctezCqM3mQFdEGX+p0T5bwIEhYfcK7wRYtu9YmRBAxLQIDAQAB';

GRANT ROLE AGENT_ROLE TO USER AGENT_SERVICE_USER;
GRANT ROLE AGENT_ROLE TO ROLE ACCOUNTADMIN;   -- lets you test as this role

-- Account identifier for the .env file
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() AS ACCOUNT_IDENTIFIER;