/* ============================================================
   FILE:      sql/07_agentic/03_action_requests.sql
   PURPOSE:   Action requests proposed by agents, awaiting human approval
   RUN AFTER: sql/07_agentic/02_agent_service_user.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

CREATE TABLE IF NOT EXISTS TRUST.ACTION_REQUEST (
    ACTION_ID          VARCHAR(100)   NOT NULL,
    ORDER_ID           VARCHAR(50)    NOT NULL,
    PART_ID            VARCHAR(50),
    PLANT_ID           VARCHAR(50),
    EVALUATION_ID      VARCHAR(100),
    TRUST_STATUS       VARCHAR(40),
    ACTION_TYPE        VARCHAR(50)    NOT NULL,
    ASSIGNED_SYSTEM    VARCHAR(200),
    ASSIGNED_OWNER     VARCHAR(200),
    TITLE              VARCHAR(500)   NOT NULL,
    MESSAGE            VARCHAR(4000),
    PAYLOAD            VARIANT,
    STATUS             VARCHAR(30)    DEFAULT 'PROPOSED',
    PROPOSED_BY        VARCHAR(100)   DEFAULT 'PLANNER_AGENT',
    PROPOSED_AT        TIMESTAMP_LTZ  DEFAULT CURRENT_TIMESTAMP(),
    DECIDED_BY         VARCHAR(200),
    DECIDED_AT         TIMESTAMP_LTZ,
    DECISION_NOTE      VARCHAR(2000),
    EXECUTED_AT        TIMESTAMP_LTZ,
    RESULT             VARIANT,

    CONSTRAINT PK_ACTION_REQUEST PRIMARY KEY (ACTION_ID),
    CONSTRAINT CK_ACTION_STATUS CHECK (
        STATUS IN ('PROPOSED', 'APPROVED', 'REJECTED', 'EXECUTED', 'VERIFIED', 'CANCELLED')
    ),
    CONSTRAINT CK_ACTION_TYPE CHECK (
        ACTION_TYPE IN (
            'REQUEST_RECOUNT', 'REQUEST_DATA_REFRESH', 'REQUEST_SOURCE_CONFIRMATION',
            'EXPEDITE_SUPPLY', 'PARTIAL_SHIPMENT_AND_EXPEDITE', 'RUN_TRUST_EVALUATION'
        )
    )
);

CREATE OR REPLACE PROCEDURE TRUST.PROPOSE_ACTION(
    P_ORDER_ID VARCHAR,
    P_PART_ID VARCHAR,
    P_PLANT_ID VARCHAR,
    P_EVALUATION_ID VARCHAR,
    P_TRUST_STATUS VARCHAR,
    P_ACTION_TYPE VARCHAR,
    P_ASSIGNED_SYSTEM VARCHAR,
    P_ASSIGNED_OWNER VARCHAR,
    P_TITLE VARCHAR,
    P_MESSAGE VARCHAR,
    P_PAYLOAD VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_EXISTING_COUNT NUMBER DEFAULT 0;
    V_EXISTING_ID    VARCHAR;
    V_ACTION_ID      VARCHAR;
    V_RESULT         VARIANT;
BEGIN
    -- Reuse an open action for the same order, part and type (no duplicates)
    SELECT COUNT(1), MAX(ACTION_ID)
    INTO :V_EXISTING_COUNT, :V_EXISTING_ID
    FROM TRUST.ACTION_REQUEST
    WHERE ORDER_ID = :P_ORDER_ID
      AND COALESCE(PART_ID, '') = COALESCE(:P_PART_ID, '')
      AND ACTION_TYPE = :P_ACTION_TYPE
      AND STATUS IN ('PROPOSED', 'APPROVED');

    IF (V_EXISTING_COUNT > 0) THEN
        V_RESULT := OBJECT_CONSTRUCT('action_id', V_EXISTING_ID, 'created', FALSE);
        RETURN V_RESULT;
    END IF;

    V_ACTION_ID := 'ACT-' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD') || '-'
                   || UPPER(LEFT(UUID_STRING(), 8));

    INSERT INTO TRUST.ACTION_REQUEST (
        ACTION_ID, ORDER_ID, PART_ID, PLANT_ID, EVALUATION_ID, TRUST_STATUS,
        ACTION_TYPE, ASSIGNED_SYSTEM, ASSIGNED_OWNER, TITLE, MESSAGE, PAYLOAD
    )
    SELECT :V_ACTION_ID, :P_ORDER_ID, :P_PART_ID, :P_PLANT_ID, :P_EVALUATION_ID,
           :P_TRUST_STATUS, :P_ACTION_TYPE, :P_ASSIGNED_SYSTEM, :P_ASSIGNED_OWNER,
           :P_TITLE, :P_MESSAGE, TRY_PARSE_JSON(:P_PAYLOAD);

    V_RESULT := OBJECT_CONSTRUCT('action_id', V_ACTION_ID, 'created', TRUE);
    RETURN V_RESULT;
END;
$$;

CREATE OR REPLACE VIEW APP.V_ACTION_QUEUE AS
SELECT
    ACTION_ID, ORDER_ID, PART_ID, PLANT_ID, TRUST_STATUS, ACTION_TYPE,
    ASSIGNED_SYSTEM, ASSIGNED_OWNER, TITLE, MESSAGE, PAYLOAD, STATUS,
    PROPOSED_BY, PROPOSED_AT, DECIDED_BY, DECIDED_AT, DECISION_NOTE
FROM TRUST.ACTION_REQUEST
ORDER BY PROPOSED_AT DESC;

-- Agent can read the queue and propose through the procedure only
GRANT SELECT ON TABLE TRUST.ACTION_REQUEST TO ROLE AGENT_ROLE;
GRANT SELECT ON VIEW APP.V_ACTION_QUEUE TO ROLE AGENT_ROLE;
GRANT USAGE ON PROCEDURE TRUST.PROPOSE_ACTION(
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR,
    VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR
) TO ROLE AGENT_ROLE;