/* ============================================================
   FILE:      sql/07_agentic/05_verification.sql
   PURPOSE:   Re-evaluation and verification of executed actions
   RUN AFTER: sql/07_agentic/04_approval_and_execution.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

ALTER TABLE TRUST.ACTION_REQUEST ADD COLUMN IF NOT EXISTS VERIFIED_AT TIMESTAMP_LTZ;
ALTER TABLE TRUST.ACTION_REQUEST ADD COLUMN IF NOT EXISTS VERIFICATION VARIANT;

-- Lets the agent re-run the trust engine without write access to trust tables
CREATE OR REPLACE PROCEDURE TRUST.RUN_TRUST_EVALUATION()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    CALL TRUST.EVALUATE_INVENTORY_TRUST('TC_USABLE_INVENTORY', '1.0');
    RETURN 'Trust evaluation completed';
END;
$$;

-- Only EXECUTED actions can be verified
CREATE OR REPLACE PROCEDURE TRUST.MARK_ACTION_VERIFIED(
    P_ACTION_ID VARCHAR,
    P_RESOLVED BOOLEAN,
    P_VERIFICATION VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_COUNT      NUMBER DEFAULT 0;
    V_STATUS     VARCHAR;
    V_NEW_STATUS VARCHAR;
    V_RESULT     VARIANT;
BEGIN
    SELECT COUNT(1), MAX(STATUS) INTO :V_COUNT, :V_STATUS
    FROM TRUST.ACTION_REQUEST
    WHERE ACTION_ID = :P_ACTION_ID;

    IF (V_COUNT = 0) THEN
        V_RESULT := OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Action not found');
        RETURN V_RESULT;
    END IF;

    IF (V_STATUS <> 'EXECUTED') THEN
        V_RESULT := OBJECT_CONSTRUCT('ok', FALSE, 'error', 'Only EXECUTED actions can be verified, current status ' || V_STATUS);
        RETURN V_RESULT;
    END IF;

    IF (P_RESOLVED) THEN
        V_NEW_STATUS := 'VERIFIED';
    ELSE
        V_NEW_STATUS := 'EXECUTED';
    END IF;

    UPDATE TRUST.ACTION_REQUEST
    SET STATUS = :V_NEW_STATUS,
        VERIFIED_AT = CURRENT_TIMESTAMP(),
        VERIFICATION = TRY_PARSE_JSON(:P_VERIFICATION)
    WHERE ACTION_ID = :P_ACTION_ID
      AND STATUS = 'EXECUTED';

    V_RESULT := OBJECT_CONSTRUCT('ok', TRUE, 'action_id', P_ACTION_ID, 'status', V_NEW_STATUS);
    RETURN V_RESULT;
END;
$$;

CREATE OR REPLACE VIEW APP.V_ACTION_QUEUE AS
SELECT
    ACTION_ID, ORDER_ID, PART_ID, PLANT_ID, TRUST_STATUS, ACTION_TYPE,
    ASSIGNED_SYSTEM, ASSIGNED_OWNER, TITLE, MESSAGE, PAYLOAD, STATUS,
    PROPOSED_BY, PROPOSED_AT, DECIDED_BY, DECIDED_AT, DECISION_NOTE,
    EXECUTED_AT, RESULT, VERIFIED_AT, VERIFICATION
FROM TRUST.ACTION_REQUEST
ORDER BY PROPOSED_AT DESC;

GRANT SELECT ON VIEW APP.V_ACTION_QUEUE TO ROLE AGENT_ROLE;
GRANT USAGE ON PROCEDURE TRUST.RUN_TRUST_EVALUATION() TO ROLE AGENT_ROLE;
GRANT USAGE ON PROCEDURE TRUST.MARK_ACTION_VERIFIED(VARCHAR, BOOLEAN, VARCHAR) TO ROLE AGENT_ROLE;