/* ============================================================
   FILE:      sql/02_views/app_views.sql
   PURPOSE:   Latest claims, cross-source comparison, latest trust status, order requirements
   RUN AFTER: sql/01_tables/trust_tables.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

/* Latest claim per source, part, plant and quantity type */
CREATE OR REPLACE VIEW APP.V_LATEST_INVENTORY_CLAIMS AS
SELECT
    CLAIM_ID, SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, PART_ID, PLANT_ID,
    QUANTITY, UNIT, QUANTITY_TYPE, EFFECTIVE_AT, EXPIRES_AT
FROM CORE.INVENTORY_CLAIM
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SOURCE_SYSTEM_ID, PART_ID, PLANT_ID, QUANTITY_TYPE
    ORDER BY EFFECTIVE_AT DESC, CREATED_AT DESC
) = 1;

/* Cross-source comparison of the latest claims */
CREATE OR REPLACE VIEW APP.V_INVENTORY_COMPARISON AS
SELECT
    PART_ID,
    PLANT_ID,
    QUANTITY_TYPE,
    UNIT,
    COUNT(DISTINCT SOURCE_SYSTEM_ID)  AS SOURCE_COUNT,
    MIN(QUANTITY)                     AS MIN_REPORTED_QUANTITY,
    MAX(QUANTITY)                     AS MAX_REPORTED_QUANTITY,
    MAX(QUANTITY) - MIN(QUANTITY)     AS ABSOLUTE_VARIANCE,
    CASE
        WHEN MAX(QUANTITY) = 0 THEN 0
        ELSE ROUND((MAX(QUANTITY) - MIN(QUANTITY)) / MAX(QUANTITY) * 100, 2)
    END                               AS VARIANCE_PERCENT,
    MAX(EFFECTIVE_AT)                 AS LATEST_EFFECTIVE_AT,
    MIN(EFFECTIVE_AT)                 AS EARLIEST_EFFECTIVE_AT
FROM APP.V_LATEST_INVENTORY_CLAIMS
GROUP BY PART_ID, PLANT_ID, QUANTITY_TYPE, UNIT;

/* Latest trust evaluation per contract and entity */
CREATE OR REPLACE VIEW APP.V_LATEST_TRUST_STATUS AS
SELECT
    EVALUATION_ID, CONTRACT_ID, CONTRACT_VERSION, ENTITY_TYPE, ENTITY_ID,
    PART_ID, PLANT_ID, ORDER_ID, METRIC_NAME, EVALUATED_VALUE, UNIT,
    STATUS, REASON_CODE, REASON, SOURCE_COUNT, MAX_VARIANCE_PERCENT,
    EVALUATED_AT, EXPIRES_AT
FROM TRUST.TRUST_EVALUATION
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CONTRACT_ID, ENTITY_TYPE, ENTITY_ID, METRIC_NAME
    ORDER BY EVALUATED_AT DESC
) = 1;

/* Orders flattened to the parts they require */
CREATE OR REPLACE VIEW APP.V_ORDER_REQUIREMENT AS
SELECT
    O.ORDER_ID, O.PLANT_ID, O.ORDER_STATUS, O.PRIORITY, O.REQUIRED_BY,
    O.ORDER_VALUE, O.CURRENCY_CODE,
    OL.ORDER_LINE_ID, OL.LINE_NUMBER, OL.PART_ID,
    P.PART_NAME, P.CRITICALITY,
    OL.REQUIRED_QUANTITY, OL.UNIT
FROM CORE.CUSTOMER_ORDER O
JOIN CORE.ORDER_LINE OL ON O.ORDER_ID = OL.ORDER_ID
JOIN CORE.PART P        ON OL.PART_ID = P.PART_ID;
