/* ============================================================
   FILE:      sql/04_seed/demo_more_scenarios.sql
   PURPOSE:   Add VERIFIED, INSUFFICIENT_EVIDENCE and STALE examples
   RUN AFTER: sql/04_seed/demo_base_data.sql
   RERUN:     NOT SAFE - inserts data
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

-- Parts
INSERT INTO CORE.PART (PART_ID, PART_NAME, BASE_UNIT, CRITICALITY)
SELECT COLUMN1, COLUMN2, 'PCS', COLUMN3 FROM VALUES
    ('PART_MOTOR_001',      'Drive Motor',      'HIGH'),
    ('PART_CONTROLLER_001', 'Controller Board', 'CRITICAL'),
    ('PART_FAN_001',        'Cooling Fan',      'MEDIUM');

-- Source records (minutes ago: 0 = fresh, 180 = stale)
INSERT INTO RAW.SOURCE_RECORD (
    SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, EXTERNAL_RECORD_ID, RECORD_TYPE,
    RECORD_VERSION, PAYLOAD, SOURCE_UPDATED_AT, INGESTION_STATUS
)
SELECT COLUMN1, COLUMN2, COLUMN3, 'INVENTORY', 1,
       OBJECT_CONSTRUCT('part', COLUMN4, 'quantity', COLUMN5, 'unit', 'PCS', 'quantity_type', 'USABLE'),
       DATEADD('MINUTE', -COLUMN6, CURRENT_TIMESTAMP()), 'VALIDATED'
FROM VALUES
    ('REC_ERP_MOT_001',  'SYS_ERP', 'ERP-INV-6001',   'ERP-MOT-01',  300, 2),
    ('REC_WMS_MOT_001',  'SYS_WMS', 'WMS-STOCK-9001', 'WH-MOTOR-A',  298, 1),
    ('REC_ERP_CTL_001',  'SYS_ERP', 'ERP-INV-6002',   'ERP-CTL-01',  80,  2),
    ('REC_ERP_FAN_001',  'SYS_ERP', 'ERP-INV-6003',   'ERP-FAN-01',  400, 180),
    ('REC_WMS_FAN_001',  'SYS_WMS', 'WMS-STOCK-9003', 'WH-FAN-A',    400, 180);

-- Inventory claims
INSERT INTO CORE.INVENTORY_CLAIM (
    CLAIM_ID, SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, PART_ID, PLANT_ID,
    QUANTITY, UNIT, QUANTITY_TYPE, EFFECTIVE_AT
)
SELECT COLUMN1, COLUMN2, COLUMN3, COLUMN4, 'PLANT_BLR_001',
       COLUMN5, 'PCS', 'USABLE', DATEADD('MINUTE', -COLUMN6, CURRENT_TIMESTAMP())
FROM VALUES
    ('CLAIM_ERP_MOT_001', 'REC_ERP_MOT_001', 'SYS_ERP', 'PART_MOTOR_001',      300, 2),
    ('CLAIM_WMS_MOT_001', 'REC_WMS_MOT_001', 'SYS_WMS', 'PART_MOTOR_001',      298, 1),
    ('CLAIM_ERP_CTL_001', 'REC_ERP_CTL_001', 'SYS_ERP', 'PART_CONTROLLER_001', 80,  2),
    ('CLAIM_ERP_FAN_001', 'REC_ERP_FAN_001', 'SYS_ERP', 'PART_FAN_001',        400, 180),
    ('CLAIM_WMS_FAN_001', 'REC_WMS_FAN_001', 'SYS_WMS', 'PART_FAN_001',        400, 180);

-- Orders: one per scenario
INSERT INTO CORE.CUSTOMER_ORDER (ORDER_ID, EXTERNAL_ORDER_ID, PLANT_ID, PRIORITY, REQUIRED_BY, ORDER_VALUE)
SELECT COLUMN1, COLUMN2, 'PLANT_BLR_001', COLUMN3, DATEADD('DAY', 3, CURRENT_TIMESTAMP()), COLUMN4
FROM VALUES
    ('ORD_002', 'CUSTOMER-ORDER-43', 'NORMAL', 90000),
    ('ORD_003', 'CUSTOMER-ORDER-44', 'HIGH',   60000),
    ('ORD_004', 'CUSTOMER-ORDER-45', 'LOW',    20000);

INSERT INTO CORE.ORDER_LINE (ORDER_LINE_ID, ORDER_ID, LINE_NUMBER, PART_ID, REQUIRED_QUANTITY, UNIT)
SELECT COLUMN1, COLUMN2, 1, COLUMN3, COLUMN4, 'PCS'
FROM VALUES
    ('ORD_002_LINE_001', 'ORD_002', 'PART_MOTOR_001',      200),
    ('ORD_003_LINE_001', 'ORD_003', 'PART_CONTROLLER_001', 50),
    ('ORD_004_LINE_001', 'ORD_004', 'PART_FAN_001',        100);

-- Evaluate all parts
CALL TRUST.EVALUATE_INVENTORY_TRUST('TC_USABLE_INVENTORY', '1.0');

-- Expected:
-- ORD_001 Battery Cell      CONFLICTED            REVIEW_REQUIRED
-- ORD_002 Drive Motor       VERIFIED (298)        CAN_FULFILL
-- ORD_003 Controller Board  INSUFFICIENT_EVIDENCE REVIEW_REQUIRED
-- ORD_004 Cooling Fan       STALE                 REVIEW_REQUIRED
SELECT ORDER_ID, PART_NAME, REQUIRED_QUANTITY, TRUST_STATUS, VERIFIED_QUANTITY, DECISION
FROM APP.V_ORDER_DECISION
ORDER BY ORDER_ID;