/* ============================================================
   FILE:      sql/04_seed/demo_base_data.sql
   PURPOSE:   Synthetic master data, source records, mappings, claims, order, definition, contract
   RUN AFTER: sql/02_views/app_views.sql
   RERUN:     NOT SAFE - inserts data. To start over, run scripts/reset_database.sql
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

/* Source systems */
INSERT INTO RAW.SOURCE_SYSTEM (SOURCE_SYSTEM_ID, SOURCE_SYSTEM_NAME, SYSTEM_TYPE, SYSTEM_OWNER, DESCRIPTION)
SELECT COLUMN1, COLUMN2, COLUMN3, COLUMN4, COLUMN5
FROM VALUES
    ('SYS_ERP',      'SAP ERP Simulator',              'ERP',             'Finance and Operations', 'Simulated ERP source for hackathon demonstration'),
    ('SYS_WMS',      'Warehouse Management Simulator', 'WMS',             'Warehouse Operations',   'Simulated warehouse source for hackathon demonstration'),
    ('SYS_SUPPLIER', 'Supplier Portal Simulator',      'SUPPLIER_PORTAL', 'Procurement',            'Simulated supplier portal for hackathon demonstration');

/* Canonical entities */
INSERT INTO CORE.SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME, COUNTRY_CODE, STATUS)
VALUES ('SUP_001', 'ABC Battery Components', 'IN', 'ACTIVE');

INSERT INTO CORE.PART (PART_ID, PART_NAME, PART_DESCRIPTION, BASE_UNIT, CRITICALITY, STATUS)
VALUES ('PART_BATTERY_001', 'Battery Cell', 'Battery cell required for final product assembly', 'PCS', 'CRITICAL', 'ACTIVE');

INSERT INTO CORE.PLANT (PLANT_ID, PLANT_NAME, CITY, COUNTRY_CODE, TIMEZONE, STATUS)
VALUES ('PLANT_BLR_001', 'Bangalore Assembly Plant', 'Bangalore', 'IN', 'Asia/Kolkata', 'ACTIVE');

INSERT INTO CORE.SUPPLIER_PART (SUPPLIER_ID, PART_ID, SUPPLIER_PART_NUMBER, LEAD_TIME_DAYS, RISK_SCORE, IS_PRIMARY_SUPPLIER, STATUS)
VALUES ('SUP_001', 'PART_BATTERY_001', 'ABC-BAT-900', 15, 62.50, TRUE, 'ACTIVE');

/* Synthetic source records (PARSE_JSON requires INSERT ... SELECT) */
INSERT INTO RAW.SOURCE_RECORD (
    SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, EXTERNAL_RECORD_ID, RECORD_TYPE, RECORD_VERSION,
    PAYLOAD, SOURCE_UPDATED_AT, PAYLOAD_HASH, INGESTION_STATUS
)
SELECT
    'REC_ERP_INV_001', 'SYS_ERP', 'ERP-INV-5001', 'INVENTORY', 1,
    PARSE_JSON('{"part_number": "ERP-BAT-01", "plant_code": "BLR01", "quantity": 500, "unit": "PCS", "quantity_type": "USABLE"}'),
    DATEADD('MINUTE', -5, CURRENT_TIMESTAMP()),
    SHA2('ERP-BAT-01|BLR01|500|PCS|USABLE', 256),
    'VALIDATED';

INSERT INTO RAW.SOURCE_RECORD (
    SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, EXTERNAL_RECORD_ID, RECORD_TYPE, RECORD_VERSION,
    PAYLOAD, SOURCE_UPDATED_AT, PAYLOAD_HASH, INGESTION_STATUS
)
SELECT
    'REC_WMS_INV_001', 'SYS_WMS', 'WMS-STOCK-8801', 'INVENTORY', 1,
    PARSE_JSON('{"sku": "WH-BATTERY-A", "warehouse": "BANGALORE-WH-1", "quantity": 120, "unit": "PCS", "quantity_type": "USABLE"}'),
    DATEADD('MINUTE', -3, CURRENT_TIMESTAMP()),
    SHA2('WH-BATTERY-A|BANGALORE-WH-1|120|PCS|USABLE', 256),
    'VALIDATED';

/* Entity mappings: source IDs -> canonical IDs */
INSERT INTO CORE.ENTITY_MAPPING (
    ENTITY_MAPPING_ID, SOURCE_SYSTEM_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID,
    CANONICAL_ENTITY_TYPE, CANONICAL_ENTITY_ID, MAPPING_STATUS, MAPPING_METHOD,
    CONFIDENCE_SCORE, APPROVED_BY, APPROVED_AT
)
SELECT COLUMN1, COLUMN2, COLUMN3, COLUMN4, COLUMN5, COLUMN6, COLUMN7, COLUMN8, COLUMN9, COLUMN10, CURRENT_TIMESTAMP()
FROM VALUES
    ('MAP_ERP_PART_001',  'SYS_ERP', 'PART',  'ERP-BAT-01',     'PART',  'PART_BATTERY_001', 'CONFIRMED', 'MANUAL', 100, 'HACKATHON_ADMIN'),
    ('MAP_WMS_PART_001',  'SYS_WMS', 'PART',  'WH-BATTERY-A',   'PART',  'PART_BATTERY_001', 'CONFIRMED', 'MANUAL', 100, 'HACKATHON_ADMIN'),
    ('MAP_ERP_PLANT_001', 'SYS_ERP', 'PLANT', 'BLR01',          'PLANT', 'PLANT_BLR_001',    'CONFIRMED', 'MANUAL', 100, 'HACKATHON_ADMIN'),
    ('MAP_WMS_PLANT_001', 'SYS_WMS', 'PLANT', 'BANGALORE-WH-1', 'PLANT', 'PLANT_BLR_001',    'CONFIRMED', 'MANUAL', 100, 'HACKATHON_ADMIN');

/* Inventory claims: same metric, part, plant, unit and comparable time -> real conflict */
INSERT INTO CORE.INVENTORY_CLAIM (
    CLAIM_ID, SOURCE_RECORD_ID, SOURCE_SYSTEM_ID, PART_ID, PLANT_ID,
    QUANTITY, UNIT, QUANTITY_TYPE, EFFECTIVE_AT
)
SELECT 'CLAIM_ERP_001', 'REC_ERP_INV_001', 'SYS_ERP', 'PART_BATTERY_001', 'PLANT_BLR_001',
       500, 'PCS', 'USABLE', DATEADD('MINUTE', -5, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CLAIM_WMS_001', 'REC_WMS_INV_001', 'SYS_WMS', 'PART_BATTERY_001', 'PLANT_BLR_001',
       120, 'PCS', 'USABLE', DATEADD('MINUTE', -3, CURRENT_TIMESTAMP());

/* Order */
INSERT INTO CORE.CUSTOMER_ORDER (ORDER_ID, EXTERNAL_ORDER_ID, PLANT_ID, ORDER_STATUS, PRIORITY, REQUIRED_BY, ORDER_VALUE, CURRENCY_CODE)
VALUES ('ORD_001', 'CUSTOMER-ORDER-42', 'PLANT_BLR_001', 'OPEN', 'HIGH', DATEADD('DAY', 2, CURRENT_TIMESTAMP()), 250000, 'USD');

INSERT INTO CORE.ORDER_LINE (ORDER_LINE_ID, ORDER_ID, LINE_NUMBER, PART_ID, REQUIRED_QUANTITY, UNIT)
VALUES ('ORD_001_LINE_001', 'ORD_001', 1, 'PART_BATTERY_001', 150, 'PCS');

/* Business definition */
INSERT INTO TRUST.BUSINESS_DEFINITION (DEFINITION_ID, DEFINITION_NAME, DEFINITION_VERSION, DESCRIPTION, FORMULA_DESCRIPTION, OWNER, APPROVAL_STATUS)
VALUES (
    'DEF_USABLE_INVENTORY', 'Usable Inventory', '1.0',
    'Inventory physically available and permitted for order fulfillment',
    'On-hand inventory minus damaged, quarantined, reserved and otherwise unavailable inventory',
    'Supply Chain Governance Team', 'APPROVED'
);

/* Trust contract (ARRAY_CONSTRUCT requires INSERT ... SELECT) */
INSERT INTO TRUST.TRUST_CONTRACT (
    CONTRACT_ID, CONTRACT_NAME, CONTRACT_VERSION, METRIC_NAME, DEFINITION_ID, DEFINITION_VERSION,
    REQUIRED_SOURCE_TYPES, MINIMUM_SOURCE_COUNT, MAXIMUM_SOURCE_AGE_MINUTES, ALLOWED_VARIANCE_PERCENT,
    REQUIRED_MAPPING_STATUS, ACTION_ON_FAILURE, IS_ACTIVE
)
SELECT
    'TC_USABLE_INVENTORY', 'Usable Inventory Verification Contract', '1.0', 'USABLE_INVENTORY',
    'DEF_USABLE_INVENTORY', '1.0', ARRAY_CONSTRUCT('ERP', 'WMS'), 2, 60, 5.00,
    'CONFIRMED', 'BLOCK_RECOMMENDATION', TRUE;
