/* ============================================================
   FILE:      sql/01_tables/core_tables.sql
   PURPOSE:   Canonical entities, mappings, inventory claims, orders
   RUN AFTER: sql/01_tables/raw_tables.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

/* Canonical business entities */
CREATE TABLE IF NOT EXISTS CORE.SUPPLIER (
    SUPPLIER_ID            VARCHAR(50)     NOT NULL,
    SUPPLIER_NAME          VARCHAR(200)    NOT NULL,
    COUNTRY_CODE           VARCHAR(10),
    STATUS                 VARCHAR(30)     DEFAULT 'ACTIVE',
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT CK_SUPPLIER_STATUS CHECK (
        STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'UNDER_REVIEW')
    )
);

CREATE TABLE IF NOT EXISTS CORE.PART (
    PART_ID                VARCHAR(50)     NOT NULL,
    PART_NAME              VARCHAR(200)    NOT NULL,
    PART_DESCRIPTION       VARCHAR(1000),
    BASE_UNIT              VARCHAR(20)     NOT NULL,
    CRITICALITY            VARCHAR(20)     DEFAULT 'MEDIUM',
    STATUS                 VARCHAR(30)     DEFAULT 'ACTIVE',
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_PART PRIMARY KEY (PART_ID),
    CONSTRAINT CK_PART_CRITICALITY CHECK (
        CRITICALITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT CK_PART_STATUS CHECK (
        STATUS IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED')
    )
);

CREATE TABLE IF NOT EXISTS CORE.PLANT (
    PLANT_ID               VARCHAR(50)     NOT NULL,
    PLANT_NAME             VARCHAR(200)    NOT NULL,
    CITY                   VARCHAR(100),
    COUNTRY_CODE           VARCHAR(10),
    TIMEZONE               VARCHAR(100),
    STATUS                 VARCHAR(30)     DEFAULT 'ACTIVE',
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_PLANT PRIMARY KEY (PLANT_ID),
    CONSTRAINT CK_PLANT_STATUS CHECK (
        STATUS IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')
    )
);

/* Supplier-part relationship */
CREATE TABLE IF NOT EXISTS CORE.SUPPLIER_PART (
    SUPPLIER_ID            VARCHAR(50)     NOT NULL,
    PART_ID                VARCHAR(50)     NOT NULL,
    SUPPLIER_PART_NUMBER   VARCHAR(100),
    LEAD_TIME_DAYS         NUMBER(10,0),
    RISK_SCORE             NUMBER(5,2),
    IS_PRIMARY_SUPPLIER    BOOLEAN         DEFAULT FALSE,
    STATUS                 VARCHAR(30)     DEFAULT 'ACTIVE',
    VALID_FROM             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO               TIMESTAMP_LTZ,

    CONSTRAINT PK_SUPPLIER_PART PRIMARY KEY (SUPPLIER_ID, PART_ID),
    CONSTRAINT FK_SUPPLIER_PART_SUPPLIER FOREIGN KEY (SUPPLIER_ID)
        REFERENCES CORE.SUPPLIER (SUPPLIER_ID),
    CONSTRAINT FK_SUPPLIER_PART_PART FOREIGN KEY (PART_ID)
        REFERENCES CORE.PART (PART_ID),
    CONSTRAINT CK_SUPPLIER_PART_RISK CHECK (
        RISK_SCORE IS NULL OR RISK_SCORE BETWEEN 0 AND 100
    ),
    CONSTRAINT CK_LEAD_TIME CHECK (
        LEAD_TIME_DAYS IS NULL OR LEAD_TIME_DAYS >= 0
    )
);

/* Source-to-canonical entity mapping */
CREATE TABLE IF NOT EXISTS CORE.ENTITY_MAPPING (
    ENTITY_MAPPING_ID      VARCHAR(100)    NOT NULL,
    SOURCE_SYSTEM_ID       VARCHAR(50)     NOT NULL,
    SOURCE_ENTITY_TYPE     VARCHAR(30)     NOT NULL,
    SOURCE_ENTITY_ID       VARCHAR(200)    NOT NULL,
    CANONICAL_ENTITY_TYPE  VARCHAR(30)     NOT NULL,
    CANONICAL_ENTITY_ID    VARCHAR(50)     NOT NULL,
    MAPPING_STATUS         VARCHAR(30)     DEFAULT 'PROPOSED',
    MAPPING_METHOD         VARCHAR(30)     DEFAULT 'MANUAL',
    CONFIDENCE_SCORE       NUMBER(5,2),
    APPROVED_BY            VARCHAR(200),
    APPROVED_AT            TIMESTAMP_LTZ,
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_ENTITY_MAPPING PRIMARY KEY (ENTITY_MAPPING_ID),
    CONSTRAINT FK_ENTITY_MAPPING_SYSTEM FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES RAW.SOURCE_SYSTEM (SOURCE_SYSTEM_ID),
    CONSTRAINT UK_SOURCE_ENTITY UNIQUE (SOURCE_SYSTEM_ID, SOURCE_ENTITY_TYPE, SOURCE_ENTITY_ID),
    CONSTRAINT CK_MAPPING_STATUS CHECK (
        MAPPING_STATUS IN ('PROPOSED', 'CONFIRMED', 'REJECTED')
    ),
    CONSTRAINT CK_MAPPING_METHOD CHECK (
        MAPPING_METHOD IN ('MANUAL', 'RULE', 'AI_SUGGESTED', 'EXACT_MATCH')
    ),
    CONSTRAINT CK_MAPPING_CONFIDENCE CHECK (
        CONFIDENCE_SCORE IS NULL OR CONFIDENCE_SCORE BETWEEN 0 AND 100
    )
);

/* Inventory claims: what one system reported, not automatic truth */
CREATE TABLE IF NOT EXISTS CORE.INVENTORY_CLAIM (
    CLAIM_ID               VARCHAR(100)    NOT NULL,
    SOURCE_RECORD_ID       VARCHAR(100)    NOT NULL,
    SOURCE_SYSTEM_ID       VARCHAR(50)     NOT NULL,
    PART_ID                VARCHAR(50)     NOT NULL,
    PLANT_ID               VARCHAR(50)     NOT NULL,
    QUANTITY               NUMBER(18,4)    NOT NULL,
    UNIT                   VARCHAR(20)     NOT NULL,
    QUANTITY_TYPE          VARCHAR(30)     NOT NULL,
    EFFECTIVE_AT           TIMESTAMP_LTZ   NOT NULL,
    EXPIRES_AT             TIMESTAMP_LTZ,
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_INVENTORY_CLAIM PRIMARY KEY (CLAIM_ID),
    CONSTRAINT FK_CLAIM_SOURCE_RECORD FOREIGN KEY (SOURCE_RECORD_ID)
        REFERENCES RAW.SOURCE_RECORD (SOURCE_RECORD_ID),
    CONSTRAINT FK_CLAIM_SOURCE_SYSTEM FOREIGN KEY (SOURCE_SYSTEM_ID)
        REFERENCES RAW.SOURCE_SYSTEM (SOURCE_SYSTEM_ID),
    CONSTRAINT FK_CLAIM_PART FOREIGN KEY (PART_ID)
        REFERENCES CORE.PART (PART_ID),
    CONSTRAINT FK_CLAIM_PLANT FOREIGN KEY (PLANT_ID)
        REFERENCES CORE.PLANT (PLANT_ID),
    CONSTRAINT CK_INVENTORY_QUANTITY CHECK (QUANTITY >= 0),
    CONSTRAINT CK_QUANTITY_TYPE CHECK (
        QUANTITY_TYPE IN ('ON_HAND', 'USABLE', 'AVAILABLE', 'RESERVED', 'DAMAGED', 'QUARANTINED', 'IN_TRANSIT')
    )
);

/* Customer orders */
CREATE TABLE IF NOT EXISTS CORE.CUSTOMER_ORDER (
    ORDER_ID               VARCHAR(50)     NOT NULL,
    EXTERNAL_ORDER_ID      VARCHAR(200),
    PLANT_ID               VARCHAR(50)     NOT NULL,
    ORDER_STATUS           VARCHAR(30)     DEFAULT 'OPEN',
    PRIORITY               VARCHAR(20)     DEFAULT 'NORMAL',
    REQUIRED_BY            TIMESTAMP_LTZ,
    ORDER_VALUE            NUMBER(18,2),
    CURRENCY_CODE          VARCHAR(10)     DEFAULT 'USD',
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_CUSTOMER_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_PLANT FOREIGN KEY (PLANT_ID)
        REFERENCES CORE.PLANT (PLANT_ID),
    CONSTRAINT CK_ORDER_STATUS CHECK (
        ORDER_STATUS IN ('OPEN', 'PLANNED', 'IN_PROGRESS', 'FULFILLED', 'CANCELLED', 'BLOCKED')
    ),
    CONSTRAINT CK_ORDER_PRIORITY CHECK (
        PRIORITY IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL')
    )
);

CREATE TABLE IF NOT EXISTS CORE.ORDER_LINE (
    ORDER_LINE_ID          VARCHAR(100)    NOT NULL,
    ORDER_ID               VARCHAR(50)     NOT NULL,
    LINE_NUMBER            NUMBER(10,0)    NOT NULL,
    PART_ID                VARCHAR(50)     NOT NULL,
    REQUIRED_QUANTITY      NUMBER(18,4)    NOT NULL,
    UNIT                   VARCHAR(20)     NOT NULL,
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_ORDER_LINE PRIMARY KEY (ORDER_LINE_ID),
    CONSTRAINT UK_ORDER_LINE_NUMBER UNIQUE (ORDER_ID, LINE_NUMBER),
    CONSTRAINT FK_ORDER_LINE_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES CORE.CUSTOMER_ORDER (ORDER_ID),
    CONSTRAINT FK_ORDER_LINE_PART FOREIGN KEY (PART_ID)
        REFERENCES CORE.PART (PART_ID),
    CONSTRAINT CK_REQUIRED_QUANTITY CHECK (REQUIRED_QUANTITY > 0)
);
