/* ============================================================
   FILE:      sql/01_tables/trust_tables.sql
   PURPOSE:   Business definitions, trust contracts, evaluations, evidence, data-quality issues
   RUN AFTER: sql/01_tables/core_tables.sql
   RERUN:     SAFE
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_TRUST_WH;
USE DATABASE SUPPLY_TRUST_DB;

/* Business definitions: approved meaning, separate from raw measurements */
CREATE TABLE IF NOT EXISTS TRUST.BUSINESS_DEFINITION (
    DEFINITION_ID          VARCHAR(100)    NOT NULL,
    DEFINITION_NAME        VARCHAR(200)    NOT NULL,
    DEFINITION_VERSION     VARCHAR(30)     NOT NULL,
    DESCRIPTION            VARCHAR(2000)   NOT NULL,
    FORMULA_DESCRIPTION    VARCHAR(2000),
    OWNER                  VARCHAR(200),
    APPROVAL_STATUS        VARCHAR(30)     DEFAULT 'DRAFT',
    VALID_FROM             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO               TIMESTAMP_LTZ,
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_BUSINESS_DEFINITION PRIMARY KEY (DEFINITION_ID, DEFINITION_VERSION),
    CONSTRAINT CK_DEFINITION_APPROVAL CHECK (
        APPROVAL_STATUS IN ('DRAFT', 'APPROVED', 'RETIRED')
    )
);

/* Trust contracts: evidence and quality conditions a metric must meet */
CREATE TABLE IF NOT EXISTS TRUST.TRUST_CONTRACT (
    CONTRACT_ID                 VARCHAR(100)    NOT NULL,
    CONTRACT_NAME               VARCHAR(200)    NOT NULL,
    CONTRACT_VERSION            VARCHAR(30)     NOT NULL,
    METRIC_NAME                 VARCHAR(200)    NOT NULL,
    DEFINITION_ID               VARCHAR(100),
    DEFINITION_VERSION          VARCHAR(30),
    REQUIRED_SOURCE_TYPES       ARRAY,
    MINIMUM_SOURCE_COUNT        NUMBER(10,0)    DEFAULT 1,
    MAXIMUM_SOURCE_AGE_MINUTES  NUMBER(10,0),
    ALLOWED_VARIANCE_PERCENT    NUMBER(8,4),
    REQUIRED_MAPPING_STATUS     VARCHAR(30)     DEFAULT 'CONFIRMED',
    ACTION_ON_FAILURE           VARCHAR(50)     DEFAULT 'REQUIRE_REVIEW',
    IS_ACTIVE                   BOOLEAN         DEFAULT TRUE,
    CREATED_AT                  TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT                  TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_TRUST_CONTRACT PRIMARY KEY (CONTRACT_ID, CONTRACT_VERSION),
    CONSTRAINT CK_MINIMUM_SOURCE_COUNT CHECK (MINIMUM_SOURCE_COUNT > 0),
    CONSTRAINT CK_MAX_SOURCE_AGE CHECK (
        MAXIMUM_SOURCE_AGE_MINUTES IS NULL OR MAXIMUM_SOURCE_AGE_MINUTES > 0
    ),
    CONSTRAINT CK_ALLOWED_VARIANCE CHECK (
        ALLOWED_VARIANCE_PERCENT IS NULL OR ALLOWED_VARIANCE_PERCENT BETWEEN 0 AND 100
    ),
    CONSTRAINT CK_REQUIRED_MAPPING_STATUS CHECK (
        REQUIRED_MAPPING_STATUS IN ('PROPOSED', 'CONFIRMED')
    ),
    CONSTRAINT CK_FAILURE_ACTION CHECK (
        ACTION_ON_FAILURE IN ('WARN', 'REQUIRE_REVIEW', 'BLOCK_RECOMMENDATION', 'BLOCK_ACTION')
    )
);

/* Trust evaluations: outcome of applying a versioned contract */
CREATE TABLE IF NOT EXISTS TRUST.TRUST_EVALUATION (
    EVALUATION_ID          VARCHAR(100)    NOT NULL,
    CONTRACT_ID            VARCHAR(100)    NOT NULL,
    CONTRACT_VERSION       VARCHAR(30)     NOT NULL,
    ENTITY_TYPE            VARCHAR(30)     NOT NULL,
    ENTITY_ID              VARCHAR(100)    NOT NULL,
    PART_ID                VARCHAR(50),
    PLANT_ID               VARCHAR(50),
    ORDER_ID               VARCHAR(50),
    METRIC_NAME            VARCHAR(200)    NOT NULL,
    EVALUATED_VALUE        NUMBER(18,4),
    UNIT                   VARCHAR(20),
    STATUS                 VARCHAR(40)     NOT NULL,
    REASON_CODE            VARCHAR(100),
    REASON                 VARCHAR(4000),
    SOURCE_COUNT           NUMBER(10,0),
    MAX_VARIANCE_PERCENT   NUMBER(8,4),
    EVALUATED_AT           TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT             TIMESTAMP_LTZ,

    CONSTRAINT PK_TRUST_EVALUATION PRIMARY KEY (EVALUATION_ID),
    CONSTRAINT FK_EVALUATION_CONTRACT FOREIGN KEY (CONTRACT_ID, CONTRACT_VERSION)
        REFERENCES TRUST.TRUST_CONTRACT (CONTRACT_ID, CONTRACT_VERSION),
    CONSTRAINT CK_EVALUATION_STATUS CHECK (
        STATUS IN ('VERIFIED', 'CONFLICTED', 'STALE', 'INSUFFICIENT_EVIDENCE', 'UNMAPPED', 'ERROR')
    )
);

/* Evaluation evidence: links each evaluation to exact records and claims */
CREATE TABLE IF NOT EXISTS TRUST.EVALUATION_EVIDENCE (
    EVALUATION_EVIDENCE_ID VARCHAR(100)    NOT NULL,
    EVALUATION_ID          VARCHAR(100)    NOT NULL,
    SOURCE_RECORD_ID       VARCHAR(100)    NOT NULL,
    CLAIM_ID               VARCHAR(100),
    EVIDENCE_ROLE          VARCHAR(30)     NOT NULL,
    EVIDENCE_VALUE         NUMBER(18,4),
    UNIT                   VARCHAR(20),
    EVIDENCE_NOTE          VARCHAR(2000),
    CREATED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_EVALUATION_EVIDENCE PRIMARY KEY (EVALUATION_EVIDENCE_ID),
    CONSTRAINT FK_EVIDENCE_EVALUATION FOREIGN KEY (EVALUATION_ID)
        REFERENCES TRUST.TRUST_EVALUATION (EVALUATION_ID),
    CONSTRAINT FK_EVIDENCE_SOURCE_RECORD FOREIGN KEY (SOURCE_RECORD_ID)
        REFERENCES RAW.SOURCE_RECORD (SOURCE_RECORD_ID),
    CONSTRAINT FK_EVIDENCE_CLAIM FOREIGN KEY (CLAIM_ID)
        REFERENCES CORE.INVENTORY_CLAIM (CLAIM_ID),
    CONSTRAINT CK_EVIDENCE_ROLE CHECK (
        EVIDENCE_ROLE IN ('SUPPORTING', 'CONFLICTING', 'STALE', 'MISSING_REFERENCE', 'INFORMATIONAL')
    )
);

/* Data-quality issue register */
CREATE TABLE IF NOT EXISTS TRUST.DATA_QUALITY_ISSUE (
    ISSUE_ID                VARCHAR(100)    NOT NULL,
    ISSUE_TYPE              VARCHAR(50)     NOT NULL,
    ENTITY_TYPE             VARCHAR(30),
    ENTITY_ID               VARCHAR(100),
    SOURCE_SYSTEM_ID        VARCHAR(50),
    SOURCE_RECORD_ID        VARCHAR(100),
    SEVERITY                VARCHAR(20)     NOT NULL,
    STATUS                  VARCHAR(30)     DEFAULT 'OPEN',
    DESCRIPTION             VARCHAR(4000)   NOT NULL,
    DETECTED_AT             TIMESTAMP_LTZ   DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT             TIMESTAMP_LTZ,
    RESOLUTION_NOTE         VARCHAR(4000),

    CONSTRAINT PK_DATA_QUALITY_ISSUE PRIMARY KEY (ISSUE_ID),
    CONSTRAINT CK_ISSUE_SEVERITY CHECK (
        SEVERITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT CK_ISSUE_STATUS CHECK (
        STATUS IN ('OPEN', 'INVESTIGATING', 'RESOLVED', 'IGNORED')
    )
);
